export interface GoogleBookItem {
  kind: string;
  id: string;
  etag: string;
  selfLink: string;
  volumeInfo: {
    title: string;
    subtitle?: string;
    authors: string[];
    publisher?: string;
    publishedDate?: string;
    description?: string;
    industryIdentifiers: {
      type: string;
      identifier: string;
    }[];
    readingModes: {
      text: boolean;
      image: boolean;
    };
    pageCount?: number;
    printType: string;
    categories?: string[];
    averageRating?: number;
    ratingsCount?: number;
    maturityRating: string;
    allowAnonLogging: boolean;
    contentVersion: string;
    panelizationSummary?: {
      containsEpubBubbles: boolean;
      containsImageBubbles: boolean;
    };
    imageLinks?: {
      smallThumbnail: string;
      thumbnail: string;
    };
    language: string;
    previewLink: string;
    infoLink: string;
    canonicalVolumeLink: string;
  };
  saleInfo?: {
    country: string;
    saleability: string;
    isEbook: boolean;
  };
  accessInfo?: {
    country: string;
    viewability: string;
    embeddable: boolean;
    publicDomain: boolean;
    textToSpeechPermission: string;
    epub: {
      isAvailable: boolean;
    };
    pdf: {
      isAvailable: boolean;
    };
    webReaderLink: string;
    accessViewStatus: string;
    quoteSharingAllowed: boolean;
  };
  searchInfo?: {
    textSnippet: string;
  };
}

// ? categories that might be found in the api of google 

export const bookCategories = [
  { name: 'Fiction', slug: 'fiction' },
  { name: 'Science Fiction', slug: 'science-fiction' },
  { name: 'Fantasy', slug: 'fantasy' },
  { name: 'Mystery & Detective', slug: 'mystery-detective' },
  { name: 'Thriller', slug: 'thriller' },
  { name: 'Romance', slug: 'romance' },
  { name: 'Historical Fiction', slug: 'historical-fiction' },
  { name: 'Young Adult', slug: 'young-adult' },
  { name: 'Children’s', slug: 'children' },
  { name: 'Nonfiction', slug: 'nonfiction' },
  { name: 'Biography & Memoir', slug: 'biography-memoir' },
  { name: 'Self-Help', slug: 'self-help' },
  { name: 'Health, Mind & Body', slug: 'health-mind-body' },
  { name: 'Religion & Spirituality', slug: 'religion-spirituality' },
  { name: 'Science', slug: 'science' },
  { name: 'History', slug: 'history' },
  { name: 'Art & Photography', slug: 'art-photography' },
  { name: 'Business & Economics', slug: 'business-economics' },
  { name: 'Travel', slug: 'travel' },
  { name: 'Cookbooks, Food & Wine', slug: 'cookbooks-food-wine' },
  { name: 'Comics & Graphic Novels', slug: 'comics-graphic-novels' },
  { name: 'Poetry', slug: 'poetry' },
  { name: 'Humor', slug: 'humor' }
];


/**
 * ! new york times api response type generated by gpt 
 */

export interface NytIsbn {
  isbn10: string | number;
  isbn13: string | number;
}

export interface NytBuyLink {
  name: string;
  url: string;
}

export interface NytBook {
  age_group: string;
  amazon_product_url: string;
  article_chapter_link?: string;
  asterisk: number;
  author: string;
  book_image: string;
  book_image_height?: number;
  book_image_width?: number;
  book_review_link: string;
  book_uri?: string;
  contributor?: string;
  contributor_note?: string;
  created_date: string;
  dagger: number;
  description: string;
  first_chapter_link: string;
  price: string;
  primary_isbn10?: string;
  primary_isbn13?: string;
  publisher: string;
  rank: number;
  rank_last_week?: number;
  sunday_review_link?: string;
  title: string;
  updated_date?: string;
  weeks_on_list?: number;
  isbns?: NytIsbn[];
  buy_links?: NytBuyLink[];
}
