export interface GoogleBookItem {
  kind: string;
  id: string;
  etag: string;
  selfLink: string;
  volumeInfo: {
    title: string;
    subtitle?: string;
    authors: string[];
    publisher?: string;
    publishedDate?: string;
    description?: string;
    industryIdentifiers: {
      type: string;
      identifier: string;
    }[];
    readingModes: {
      text: boolean;
      image: boolean;
    };
    pageCount?: number;
    printType: string;
    categories?: string[];
    averageRating?: number;
    ratingsCount?: number;
    maturityRating: string;
    allowAnonLogging: boolean;
    contentVersion: string;
    panelizationSummary?: {
      containsEpubBubbles: boolean;
      containsImageBubbles: boolean;
    };
    imageLinks?: {
      smallThumbnail: string;
      thumbnail: string;
    };
    language: string;
    previewLink: string;
    infoLink: string;
    canonicalVolumeLink: string;
  };
  saleInfo?: {
    country: string;
    saleability: string;
    isEbook: boolean;
  };
  accessInfo?: {
    country: string;
    viewability: string;
    embeddable: boolean;
    publicDomain: boolean;
    textToSpeechPermission: string;
    epub: {
      isAvailable: boolean;
    };
    pdf: {
      isAvailable: boolean;
    };
    webReaderLink: string;
    accessViewStatus: string;
    quoteSharingAllowed: boolean;
  };
  searchInfo?: {
    textSnippet: string;
  };
}



/**
 * ! new york times api response type generated by gpt 
 */

export interface NytIsbn {
  isbn10: string;
  isbn13: string;
}

export interface NytBuyLink {
  name: string;
  url: string;
}

export interface NytBook {
  age_group: string;
  amazon_product_url: string;
  article_chapter_link?: string;
  asterisk: number;
  author: string;
  book_image: string;
  book_image_height?: number;
  book_image_width?: number;
  book_review_link: string;
  book_uri?: string;
  contributor?: string;
  contributor_note?: string;
  created_date: string;
  dagger: number;
  description: string;
  first_chapter_link: string;
  price: string;
  primary_isbn10?: string;
  primary_isbn13?: string;
  publisher: string;
  rank: number;
  rank_last_week?: number;
  sunday_review_link?: string;
  title: string;
  updated_date?: string;
  weeks_on_list?: number;
  isbns?: NytIsbn[];
  buy_links?: NytBuyLink[];
}
